name: Push commit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # At 00:00 UTC on the 1st of every month
permissions:
  contents: write
jobs:
  whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Append to whitespace database
        run: echo -n " " >> whitespace.txt
      - name: Commit report
        run: |
          git config --global user.name 'White Space Bot'
          git config --global user.email 'whitespace[bot]@users.noreply.github.com'
          git add whitespace.txt
          git commit -am "Automated update"
          git push
